# Media configuration allowing you to browse/upload across your media folders
media:
  - name: docs_media
    label: Media
    input: docs/media
    output: /media
    
# File Map access
  - name: map_pdf
    label: File Map
    input: docs/media/file-map
    output: ../../media/file-map

# Content Collections
content:
  - name: docs
    label: documentation
    type: collection
    path: docs
    exclude:
      - "**/media/**"
      - "**/images/**"
    format: yaml-frontmatter
    filename: "{primary}.md"

    view:
      fields:
        - title
        - description
      primary: title

    fields:
      - name: title
        label: Title
        type: string
        required: true
        
      - name: hide
        label: Hide UI Elements
        type: select
        options:
          multiple: true
          values: ["navigation", "toc", "path", "footer", "feedback"]

      - name: body
        label: Page Content
        type: rich-text
